### ISSUE TITLE
www.drupalapprentice.uk does not resolve

### ISSUE THREAD

**Issue by crispinread** [OpenDrupal/drupal-apprenice-1page#7]

**Comment by crispinread** [comment]
www goes to the nginx page :/

without www its fine tho

**Comment by hedleysmith** [comment]
I've added a ticket to the server support team asking them to update the VHost configuration, so they'll be on this soon

**Comment by hedleysmith** [comment]
This is fixed now, and I've just requested that the non-www resolved to the www. subdomain to keep things simple
